# Generated by Django 4.1.6 on 2023-02-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_categorias_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(auto_now=True)),
                ('tipo_cliente', models.CharField(choices=[('F', 'Cliente Free'), ('P', 'Cliente Premium'), ('M', 'Cliente Master')], max_length=1)),
            ],
        ),
    ]
