# Generated by Django 4.1.6 on 2023-02-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[('F', 'Cliente Free'), ('P', 'Cliente Premium'), ('M', 'Cliente Master')], default='F', max_length=1),
        ),
    ]
