# Generated by Django 4.1.6 on 2023-02-24 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('M', 'Master')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1, message='O preço deve ser igual ou maior que 1 real'), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='A quantidade deve ser igual ou maior que 0 ')]),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now=True)),
                ('tipo_pagamento', models.CharField(choices=[('C', 'Cartão Crédito'), ('D', 'Cartão Débito'), ('P', 'PIX'), ('B', 'Boleto')], default='P', max_length=1)),
                ('status_pagamento', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Recusado'), ('P', 'Pendente')], default='P', max_length=1)),
                ('status_pedido', models.CharField(choices=[('X', 'Cancelado'), ('E', 'Entregue'), ('C', 'À Caminho'), ('P', 'Em Preparação'), ('A', 'Aguardando')], default='A', max_length=1)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'A quantidade não pode ser menor que 1')])),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedidos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.produtos')),
            ],
        ),
    ]
